# cloudbuild.yaml
steps:
  # Step 1 -- Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/helloworld/helloworld:$SHORT_SHA'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/helloworld/helloworld:latest'
      - '.'

  # Step 2 -- Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/helloworld/helloworld:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/helloworld/helloworld:latest'

# Image pushed to Artifact Registry
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/helloworld/helloworld:$SHORT_SHA'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/helloworld/helloworld:latest'
# Timeout for the entire build
timeout: '1200s'
